apiVersion: 1
datasources:
  - name: Demo Prometheus
    type: prometheus
    uid: demo-prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  - name: Demo Loki
    type: loki
    uid: demo-loki
    access: proxy
    url: http://loki:3100
